baseurl = "https://blog.rsquaredacademy.com/"
languageCode = "en-us"
title = "Rsquared Academy Blog"
theme = "blackburn"
copyright = "&copy; 2014-2019. All rights reserved."
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
post = "/:slug/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Explore..Discover..Learn"
  description = "Rsquared Academy Blog"
  twitterAuthor = "@hebbaliaravind"
  twitterSite = "@rsquaredacademy"
  brand = "![Rsquared Academy Logo](/img/logos.png)"
  googleAnalytics = "UA-57270671-6"
  disqus = ""
  [params.logo]
    url = "logo.jpeg"
    width = 50
    height = 50
    alt = "Aravind Hebbali"

  # CSS name for highlight.js
  highlightjs = "Github"
  highlightjs_extra_languages = ["r", "yaml", "bash"]
  dateFormat = "02 Jan 2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Start here"
    pre = "<i class='fa fa-road fa-fw'></i>"
    weight = 2
    identifier = "start-here"
    url = "/start-here"
  [[menu.main]]
    name = " Data Science Courses"
    pre = "<i class='fa fa-graduation-cap fa-fw'></i>"
    weight = 3
    identifier = "courses1"
    url = "https://rsquared-academy.thinkific.com/" 
  [[menu.main]]
    name = " Risk Management Courses"
    pre = "<i class='fa fa-graduation-cap fa-fw'></i>"
    weight = 4
    identifier = "courses2"
    url = "https://www.riskycall.com/" 
  [[menu.main]]
    name = "Shiny Apps"
    pre = "<i class='fa fa-cube fa-fw'></i>"
    weight = 6
    identifier = "app"
    url = "https://apps.rsquaredacademy.com/" 
  [[menu.main]]
    name = "R Packages"
    pre = "<i class='fa fa-code fa-fw'></i>"
    weight = 7
    identifier = "package"
    url = "https://pkgs.rsquaredacademy.com/" 
  [[menu.main]]
    name = "e-books"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 8
    identifier = "ebooks"
    url = "https://ebooks.rsquaredacademy.com/"   
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 9
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "R Bloggers"
    pre = "<i class='fa fa-cubes fa-fw'></i>"
    weight = 10
    identifier = "r-blogger"
    url = "https://r-bloggers.com/" 

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "rsquaredacademy"
  facebook = "rsquaredacademy"

  # SNS photo/video sharing
  youtube = "rsquaredin"
  slideshare = "rsquaredin"
  linkedin = "rsquared-academy"

  # Techie
github = "rsquaredacademy"