[[redirects]]
  from = "https://blog.rsquaredacademy.com/tags/ggplot2"
  to = "https://blog.rsquaredacademy.com/data-visualization/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/tags/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/categories/"
  to = "/"
  status = 301
  force = true  